INSERT INTO "PARAMETER" VALUES (1,'ESG','Environment','E');
INSERT INTO "PARAMETER" VALUES (2,'ESG','Social','S');
INSERT INTO "PARAMETER" VALUES (3,'ESG','Governance','G');
INSERT INTO "USER" VALUES (1,'mustang','TLGbWGfbiCpWOMtRvAK73g==',NULL);
